//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace map_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyList
    {
        public long ParcelNumb { get; set; }
        public string ADDRESS { get; set; }
        public string StreetAddress { get; set; }
        public string StreetName { get; set; }
        public string StreetSuffix { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<double> LAT { get; set; }
        public Nullable<double> LONG { get; set; }
        public string STATUS { get; set; }
        public string FLD_ZONE { get; set; }
        public string FLOODWAY { get; set; }
        public Nullable<double> BFE { get; set; }
        public Nullable<double> FIRM_DATE { get; set; }
        public string FIRM_PAN { get; set; }
        public string SUFFIX { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom { get; set; }
    }
}
